name: accessories_store
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^8.0.0
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.1
  equatable: ^2.0.8
  flutter_svg: ^2.2.3
  lottie: ^3.3.2
  cached_network_image: ^3.4.1
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.8
  awesome_snackbar_content: ^0.1.8
  animated_snack_bar: ^0.4.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix:
  ignore_comments: true